local constants = {
    AUTO_COLLECT_RADIUS = 4,
    MANHATTAN_DISTANCE_TO_START_BOX_SELECTION = 64,
    GET_MOUSE_POS_PERIOD = 0.1,
    SELECTION_BOX_TINT = {1, 1, 1, 0.15}, -- RGBA
    UNSELECTABLE_TAGS = {"FX", "NOCLICK", "DECOR", "INLIMBO"},
}

return constants
